/**
 * Autogenerated by Thrift Compiler (0.9.3)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "me_constants.h"

namespace RPC {

const meConstants g_me_constants;

meConstants::meConstants() {
}

} // namespace

