/**
 * Autogenerated by Thrift Compiler (0.9.3)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef me_CONSTANTS_H
#define me_CONSTANTS_H

#include "me_types.h"

namespace RPC {

class meConstants {
 public:
  meConstants();

};

extern const meConstants g_me_constants;

} // namespace

#endif
