/**
 * Autogenerated by Thrift Compiler (0.9.3)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef Proxy_H
#define Proxy_H

#include <thrift/TDispatchProcessor.h>
#include <thrift/async/TConcurrentClientSyncInfo.h>
#include "proxy_types.h"

namespace Proxy {

#ifdef _WIN32
  #pragma warning( push )
  #pragma warning (disable : 4250 ) //inheriting methods via dominance 
#endif

class ProxyIf {
 public:
  virtual ~ProxyIf() {}
  virtual void ping() = 0;
  virtual int32_t getURL(const std::string& url) = 0;
};

class ProxyIfFactory {
 public:
  typedef ProxyIf Handler;

  virtual ~ProxyIfFactory() {}

  virtual ProxyIf* getHandler(const ::apache::thrift::TConnectionInfo& connInfo) = 0;
  virtual void releaseHandler(ProxyIf* /* handler */) = 0;
};

class ProxyIfSingletonFactory : virtual public ProxyIfFactory {
 public:
  ProxyIfSingletonFactory(const boost::shared_ptr<ProxyIf>& iface) : iface_(iface) {}
  virtual ~ProxyIfSingletonFactory() {}

  virtual ProxyIf* getHandler(const ::apache::thrift::TConnectionInfo&) {
    return iface_.get();
  }
  virtual void releaseHandler(ProxyIf* /* handler */) {}

 protected:
  boost::shared_ptr<ProxyIf> iface_;
};

class ProxyNull : virtual public ProxyIf {
 public:
  virtual ~ProxyNull() {}
  void ping() {
    return;
  }
  int32_t getURL(const std::string& /* url */) {
    int32_t _return = 0;
    return _return;
  }
};


class Proxy_ping_args {
 public:

  Proxy_ping_args(const Proxy_ping_args&);
  Proxy_ping_args& operator=(const Proxy_ping_args&);
  Proxy_ping_args() {
  }

  virtual ~Proxy_ping_args() throw();

  bool operator == (const Proxy_ping_args & /* rhs */) const
  {
    return true;
  }
  bool operator != (const Proxy_ping_args &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const Proxy_ping_args & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};


class Proxy_ping_pargs {
 public:


  virtual ~Proxy_ping_pargs() throw();

  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};


class Proxy_ping_result {
 public:

  Proxy_ping_result(const Proxy_ping_result&);
  Proxy_ping_result& operator=(const Proxy_ping_result&);
  Proxy_ping_result() {
  }

  virtual ~Proxy_ping_result() throw();

  bool operator == (const Proxy_ping_result & /* rhs */) const
  {
    return true;
  }
  bool operator != (const Proxy_ping_result &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const Proxy_ping_result & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};


class Proxy_ping_presult {
 public:


  virtual ~Proxy_ping_presult() throw();

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);

};

typedef struct _Proxy_getURL_args__isset {
  _Proxy_getURL_args__isset() : url(false) {}
  bool url :1;
} _Proxy_getURL_args__isset;

class Proxy_getURL_args {
 public:

  Proxy_getURL_args(const Proxy_getURL_args&);
  Proxy_getURL_args& operator=(const Proxy_getURL_args&);
  Proxy_getURL_args() : url() {
  }

  virtual ~Proxy_getURL_args() throw();
  std::string url;

  _Proxy_getURL_args__isset __isset;

  void __set_url(const std::string& val);

  bool operator == (const Proxy_getURL_args & rhs) const
  {
    if (!(url == rhs.url))
      return false;
    return true;
  }
  bool operator != (const Proxy_getURL_args &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const Proxy_getURL_args & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};


class Proxy_getURL_pargs {
 public:


  virtual ~Proxy_getURL_pargs() throw();
  const std::string* url;

  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _Proxy_getURL_result__isset {
  _Proxy_getURL_result__isset() : success(false) {}
  bool success :1;
} _Proxy_getURL_result__isset;

class Proxy_getURL_result {
 public:

  Proxy_getURL_result(const Proxy_getURL_result&);
  Proxy_getURL_result& operator=(const Proxy_getURL_result&);
  Proxy_getURL_result() : success(0) {
  }

  virtual ~Proxy_getURL_result() throw();
  int32_t success;

  _Proxy_getURL_result__isset __isset;

  void __set_success(const int32_t val);

  bool operator == (const Proxy_getURL_result & rhs) const
  {
    if (!(success == rhs.success))
      return false;
    return true;
  }
  bool operator != (const Proxy_getURL_result &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const Proxy_getURL_result & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _Proxy_getURL_presult__isset {
  _Proxy_getURL_presult__isset() : success(false) {}
  bool success :1;
} _Proxy_getURL_presult__isset;

class Proxy_getURL_presult {
 public:


  virtual ~Proxy_getURL_presult() throw();
  int32_t* success;

  _Proxy_getURL_presult__isset __isset;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);

};

class ProxyClient : virtual public ProxyIf {
 public:
  ProxyClient(boost::shared_ptr< ::apache::thrift::protocol::TProtocol> prot) {
    setProtocol(prot);
  }
  ProxyClient(boost::shared_ptr< ::apache::thrift::protocol::TProtocol> iprot, boost::shared_ptr< ::apache::thrift::protocol::TProtocol> oprot) {
    setProtocol(iprot,oprot);
  }
 private:
  void setProtocol(boost::shared_ptr< ::apache::thrift::protocol::TProtocol> prot) {
  setProtocol(prot,prot);
  }
  void setProtocol(boost::shared_ptr< ::apache::thrift::protocol::TProtocol> iprot, boost::shared_ptr< ::apache::thrift::protocol::TProtocol> oprot) {
    piprot_=iprot;
    poprot_=oprot;
    iprot_ = iprot.get();
    oprot_ = oprot.get();
  }
 public:
  boost::shared_ptr< ::apache::thrift::protocol::TProtocol> getInputProtocol() {
    return piprot_;
  }
  boost::shared_ptr< ::apache::thrift::protocol::TProtocol> getOutputProtocol() {
    return poprot_;
  }
  void ping();
  void send_ping();
  void recv_ping();
  int32_t getURL(const std::string& url);
  void send_getURL(const std::string& url);
  int32_t recv_getURL();
 protected:
  boost::shared_ptr< ::apache::thrift::protocol::TProtocol> piprot_;
  boost::shared_ptr< ::apache::thrift::protocol::TProtocol> poprot_;
  ::apache::thrift::protocol::TProtocol* iprot_;
  ::apache::thrift::protocol::TProtocol* oprot_;
};

class ProxyProcessor : public ::apache::thrift::TDispatchProcessor {
 protected:
  boost::shared_ptr<ProxyIf> iface_;
  virtual bool dispatchCall(::apache::thrift::protocol::TProtocol* iprot, ::apache::thrift::protocol::TProtocol* oprot, const std::string& fname, int32_t seqid, void* callContext);
 private:
  typedef  void (ProxyProcessor::*ProcessFunction)(int32_t, ::apache::thrift::protocol::TProtocol*, ::apache::thrift::protocol::TProtocol*, void*);
  typedef std::map<std::string, ProcessFunction> ProcessMap;
  ProcessMap processMap_;
  void process_ping(int32_t seqid, ::apache::thrift::protocol::TProtocol* iprot, ::apache::thrift::protocol::TProtocol* oprot, void* callContext);
  void process_getURL(int32_t seqid, ::apache::thrift::protocol::TProtocol* iprot, ::apache::thrift::protocol::TProtocol* oprot, void* callContext);
 public:
  ProxyProcessor(boost::shared_ptr<ProxyIf> iface) :
    iface_(iface) {
    processMap_["ping"] = &ProxyProcessor::process_ping;
    processMap_["getURL"] = &ProxyProcessor::process_getURL;
  }

  virtual ~ProxyProcessor() {}
};

class ProxyProcessorFactory : public ::apache::thrift::TProcessorFactory {
 public:
  ProxyProcessorFactory(const ::boost::shared_ptr< ProxyIfFactory >& handlerFactory) :
      handlerFactory_(handlerFactory) {}

  ::boost::shared_ptr< ::apache::thrift::TProcessor > getProcessor(const ::apache::thrift::TConnectionInfo& connInfo);

 protected:
  ::boost::shared_ptr< ProxyIfFactory > handlerFactory_;
};

class ProxyMultiface : virtual public ProxyIf {
 public:
  ProxyMultiface(std::vector<boost::shared_ptr<ProxyIf> >& ifaces) : ifaces_(ifaces) {
  }
  virtual ~ProxyMultiface() {}
 protected:
  std::vector<boost::shared_ptr<ProxyIf> > ifaces_;
  ProxyMultiface() {}
  void add(boost::shared_ptr<ProxyIf> iface) {
    ifaces_.push_back(iface);
  }
 public:
  void ping() {
    size_t sz = ifaces_.size();
    size_t i = 0;
    for (; i < (sz - 1); ++i) {
      ifaces_[i]->ping();
    }
    ifaces_[i]->ping();
  }

  int32_t getURL(const std::string& url) {
    size_t sz = ifaces_.size();
    size_t i = 0;
    for (; i < (sz - 1); ++i) {
      ifaces_[i]->getURL(url);
    }
    return ifaces_[i]->getURL(url);
  }

};

// The 'concurrent' client is a thread safe client that correctly handles
// out of order responses.  It is slower than the regular client, so should
// only be used when you need to share a connection among multiple threads
class ProxyConcurrentClient : virtual public ProxyIf {
 public:
  ProxyConcurrentClient(boost::shared_ptr< ::apache::thrift::protocol::TProtocol> prot) {
    setProtocol(prot);
  }
  ProxyConcurrentClient(boost::shared_ptr< ::apache::thrift::protocol::TProtocol> iprot, boost::shared_ptr< ::apache::thrift::protocol::TProtocol> oprot) {
    setProtocol(iprot,oprot);
  }
 private:
  void setProtocol(boost::shared_ptr< ::apache::thrift::protocol::TProtocol> prot) {
  setProtocol(prot,prot);
  }
  void setProtocol(boost::shared_ptr< ::apache::thrift::protocol::TProtocol> iprot, boost::shared_ptr< ::apache::thrift::protocol::TProtocol> oprot) {
    piprot_=iprot;
    poprot_=oprot;
    iprot_ = iprot.get();
    oprot_ = oprot.get();
  }
 public:
  boost::shared_ptr< ::apache::thrift::protocol::TProtocol> getInputProtocol() {
    return piprot_;
  }
  boost::shared_ptr< ::apache::thrift::protocol::TProtocol> getOutputProtocol() {
    return poprot_;
  }
  void ping();
  int32_t send_ping();
  void recv_ping(const int32_t seqid);
  int32_t getURL(const std::string& url);
  int32_t send_getURL(const std::string& url);
  int32_t recv_getURL(const int32_t seqid);
 protected:
  boost::shared_ptr< ::apache::thrift::protocol::TProtocol> piprot_;
  boost::shared_ptr< ::apache::thrift::protocol::TProtocol> poprot_;
  ::apache::thrift::protocol::TProtocol* iprot_;
  ::apache::thrift::protocol::TProtocol* oprot_;
  ::apache::thrift::async::TConcurrentClientSyncInfo sync_;
};

#ifdef _WIN32
  #pragma warning( pop )
#endif

} // namespace

#endif
