/**
 * Autogenerated by Thrift Compiler (0.9.3)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef ProxyServer_H
#define ProxyServer_H

#include <thrift/TDispatchProcessor.h>
#include <thrift/async/TConcurrentClientSyncInfo.h>
#include "me_types.h"

namespace RPC {

#ifdef _WIN32
  #pragma warning( push )
  #pragma warning (disable : 4250 ) //inheriting methods via dominance 
#endif

class ProxyServerIf {
 public:
  virtual ~ProxyServerIf() {}
  virtual int32_t getCurrentTime() = 0;
};

class ProxyServerIfFactory {
 public:
  typedef ProxyServerIf Handler;

  virtual ~ProxyServerIfFactory() {}

  virtual ProxyServerIf* getHandler(const ::apache::thrift::TConnectionInfo& connInfo) = 0;
  virtual void releaseHandler(ProxyServerIf* /* handler */) = 0;
};

class ProxyServerIfSingletonFactory : virtual public ProxyServerIfFactory {
 public:
  ProxyServerIfSingletonFactory(const boost::shared_ptr<ProxyServerIf>& iface) : iface_(iface) {}
  virtual ~ProxyServerIfSingletonFactory() {}

  virtual ProxyServerIf* getHandler(const ::apache::thrift::TConnectionInfo&) {
    return iface_.get();
  }
  virtual void releaseHandler(ProxyServerIf* /* handler */) {}

 protected:
  boost::shared_ptr<ProxyServerIf> iface_;
};

class ProxyServerNull : virtual public ProxyServerIf {
 public:
  virtual ~ProxyServerNull() {}
  int32_t getCurrentTime() {
    int32_t _return = 0;
    return _return;
  }
};


class ProxyServer_getCurrentTime_args {
 public:

  ProxyServer_getCurrentTime_args(const ProxyServer_getCurrentTime_args&);
  ProxyServer_getCurrentTime_args& operator=(const ProxyServer_getCurrentTime_args&);
  ProxyServer_getCurrentTime_args() {
  }

  virtual ~ProxyServer_getCurrentTime_args() throw();

  bool operator == (const ProxyServer_getCurrentTime_args & /* rhs */) const
  {
    return true;
  }
  bool operator != (const ProxyServer_getCurrentTime_args &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const ProxyServer_getCurrentTime_args & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};


class ProxyServer_getCurrentTime_pargs {
 public:


  virtual ~ProxyServer_getCurrentTime_pargs() throw();

  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _ProxyServer_getCurrentTime_result__isset {
  _ProxyServer_getCurrentTime_result__isset() : success(false) {}
  bool success :1;
} _ProxyServer_getCurrentTime_result__isset;

class ProxyServer_getCurrentTime_result {
 public:

  ProxyServer_getCurrentTime_result(const ProxyServer_getCurrentTime_result&);
  ProxyServer_getCurrentTime_result& operator=(const ProxyServer_getCurrentTime_result&);
  ProxyServer_getCurrentTime_result() : success(0) {
  }

  virtual ~ProxyServer_getCurrentTime_result() throw();
  int32_t success;

  _ProxyServer_getCurrentTime_result__isset __isset;

  void __set_success(const int32_t val);

  bool operator == (const ProxyServer_getCurrentTime_result & rhs) const
  {
    if (!(success == rhs.success))
      return false;
    return true;
  }
  bool operator != (const ProxyServer_getCurrentTime_result &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const ProxyServer_getCurrentTime_result & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _ProxyServer_getCurrentTime_presult__isset {
  _ProxyServer_getCurrentTime_presult__isset() : success(false) {}
  bool success :1;
} _ProxyServer_getCurrentTime_presult__isset;

class ProxyServer_getCurrentTime_presult {
 public:


  virtual ~ProxyServer_getCurrentTime_presult() throw();
  int32_t* success;

  _ProxyServer_getCurrentTime_presult__isset __isset;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);

};

class ProxyServerClient : virtual public ProxyServerIf {
 public:
  ProxyServerClient(boost::shared_ptr< ::apache::thrift::protocol::TProtocol> prot) {
    setProtocol(prot);
  }
  ProxyServerClient(boost::shared_ptr< ::apache::thrift::protocol::TProtocol> iprot, boost::shared_ptr< ::apache::thrift::protocol::TProtocol> oprot) {
    setProtocol(iprot,oprot);
  }
 private:
  void setProtocol(boost::shared_ptr< ::apache::thrift::protocol::TProtocol> prot) {
  setProtocol(prot,prot);
  }
  void setProtocol(boost::shared_ptr< ::apache::thrift::protocol::TProtocol> iprot, boost::shared_ptr< ::apache::thrift::protocol::TProtocol> oprot) {
    piprot_=iprot;
    poprot_=oprot;
    iprot_ = iprot.get();
    oprot_ = oprot.get();
  }
 public:
  boost::shared_ptr< ::apache::thrift::protocol::TProtocol> getInputProtocol() {
    return piprot_;
  }
  boost::shared_ptr< ::apache::thrift::protocol::TProtocol> getOutputProtocol() {
    return poprot_;
  }
  int32_t getCurrentTime();
  void send_getCurrentTime();
  int32_t recv_getCurrentTime();
 protected:
  boost::shared_ptr< ::apache::thrift::protocol::TProtocol> piprot_;
  boost::shared_ptr< ::apache::thrift::protocol::TProtocol> poprot_;
  ::apache::thrift::protocol::TProtocol* iprot_;
  ::apache::thrift::protocol::TProtocol* oprot_;
};

class ProxyServerProcessor : public ::apache::thrift::TDispatchProcessor {
 protected:
  boost::shared_ptr<ProxyServerIf> iface_;
  virtual bool dispatchCall(::apache::thrift::protocol::TProtocol* iprot, ::apache::thrift::protocol::TProtocol* oprot, const std::string& fname, int32_t seqid, void* callContext);
 private:
  typedef  void (ProxyServerProcessor::*ProcessFunction)(int32_t, ::apache::thrift::protocol::TProtocol*, ::apache::thrift::protocol::TProtocol*, void*);
  typedef std::map<std::string, ProcessFunction> ProcessMap;
  ProcessMap processMap_;
  void process_getCurrentTime(int32_t seqid, ::apache::thrift::protocol::TProtocol* iprot, ::apache::thrift::protocol::TProtocol* oprot, void* callContext);
 public:
  ProxyServerProcessor(boost::shared_ptr<ProxyServerIf> iface) :
    iface_(iface) {
    processMap_["getCurrentTime"] = &ProxyServerProcessor::process_getCurrentTime;
  }

  virtual ~ProxyServerProcessor() {}
};

class ProxyServerProcessorFactory : public ::apache::thrift::TProcessorFactory {
 public:
  ProxyServerProcessorFactory(const ::boost::shared_ptr< ProxyServerIfFactory >& handlerFactory) :
      handlerFactory_(handlerFactory) {}

  ::boost::shared_ptr< ::apache::thrift::TProcessor > getProcessor(const ::apache::thrift::TConnectionInfo& connInfo);

 protected:
  ::boost::shared_ptr< ProxyServerIfFactory > handlerFactory_;
};

class ProxyServerMultiface : virtual public ProxyServerIf {
 public:
  ProxyServerMultiface(std::vector<boost::shared_ptr<ProxyServerIf> >& ifaces) : ifaces_(ifaces) {
  }
  virtual ~ProxyServerMultiface() {}
 protected:
  std::vector<boost::shared_ptr<ProxyServerIf> > ifaces_;
  ProxyServerMultiface() {}
  void add(boost::shared_ptr<ProxyServerIf> iface) {
    ifaces_.push_back(iface);
  }
 public:
  int32_t getCurrentTime() {
    size_t sz = ifaces_.size();
    size_t i = 0;
    for (; i < (sz - 1); ++i) {
      ifaces_[i]->getCurrentTime();
    }
    return ifaces_[i]->getCurrentTime();
  }

};

// The 'concurrent' client is a thread safe client that correctly handles
// out of order responses.  It is slower than the regular client, so should
// only be used when you need to share a connection among multiple threads
class ProxyServerConcurrentClient : virtual public ProxyServerIf {
 public:
  ProxyServerConcurrentClient(boost::shared_ptr< ::apache::thrift::protocol::TProtocol> prot) {
    setProtocol(prot);
  }
  ProxyServerConcurrentClient(boost::shared_ptr< ::apache::thrift::protocol::TProtocol> iprot, boost::shared_ptr< ::apache::thrift::protocol::TProtocol> oprot) {
    setProtocol(iprot,oprot);
  }
 private:
  void setProtocol(boost::shared_ptr< ::apache::thrift::protocol::TProtocol> prot) {
  setProtocol(prot,prot);
  }
  void setProtocol(boost::shared_ptr< ::apache::thrift::protocol::TProtocol> iprot, boost::shared_ptr< ::apache::thrift::protocol::TProtocol> oprot) {
    piprot_=iprot;
    poprot_=oprot;
    iprot_ = iprot.get();
    oprot_ = oprot.get();
  }
 public:
  boost::shared_ptr< ::apache::thrift::protocol::TProtocol> getInputProtocol() {
    return piprot_;
  }
  boost::shared_ptr< ::apache::thrift::protocol::TProtocol> getOutputProtocol() {
    return poprot_;
  }
  int32_t getCurrentTime();
  int32_t send_getCurrentTime();
  int32_t recv_getCurrentTime(const int32_t seqid);
 protected:
  boost::shared_ptr< ::apache::thrift::protocol::TProtocol> piprot_;
  boost::shared_ptr< ::apache::thrift::protocol::TProtocol> poprot_;
  ::apache::thrift::protocol::TProtocol* iprot_;
  ::apache::thrift::protocol::TProtocol* oprot_;
  ::apache::thrift::async::TConcurrentClientSyncInfo sync_;
};

#ifdef _WIN32
  #pragma warning( pop )
#endif

} // namespace

#endif
